### ISSUE TITLE
implementation of `tuple_element<i,camp::tuple<T...>>` not allowing structured binding using `const auto`

### ISSUE THREAD

**Issue by rrsettgast** [LLNL/camp#139]
Hello,
In the StructuredBindings unit test, if I change the return type to `const auto` as such:
```c++
TEST(CampTuple, StructuredBindings)
{
  auto t = camp::make_tuple(3, 9.9);
  const auto [a, b] = t;
  ASSERT_EQ(a, 3);
  ASSERT_NEAR(b, 9.9, 1e-15);
}
```
I get the following error:
```
[ 34%] Building CXX object test/CMakeFiles/tuple.dir/tuple.cpp.o
cd /usr/workspace/settgast/Codes/geosx/camp/build/test && /usr/lib64/ccache/c++ -DGTEST_HAS_DEATH_TEST=0 -I/usr/workspace/settgast/Codes/geosx/camp/include -I/usr/workspace/settgast/Codes/geosx/camp/build/include -isystem /usr/workspace/settgast/Codes/geosx/camp/extern/blt/thirdparty_builtin/googletest/googletest/include -Wall -Wextra      -fPIE -std=c++17 -MD -MT test/CMakeFiles/tuple.dir/tuple.cpp.o -MF CMakeFiles/tuple.dir/tuple.cpp.o.d -o CMakeFiles/tuple.dir/tuple.cpp.o -c /usr/workspace/settgast/Codes/geosx/camp/test/tuple.cpp
/usr/workspace/settgast/Codes/geosx/camp/test/tuple.cpp: In member function ‘virtual void CampTuple_StructuredBindings_Test::TestBody()’:
/usr/workspace/settgast/Codes/geosx/camp/test/tuple.cpp:362:23: error: binding reference of type ‘int&&’ to ‘camp::tuple_element_t<0, camp::tuple<int, double> >’ {aka ‘const int’} discards qualifiers
   const auto [a, b] = t;
                       ^
/usr/workspace/settgast/Codes/geosx/camp/test/tuple.cpp:362:23: error: binding reference of type ‘double&&’ to ‘camp::tuple_element_t<1, camp::tuple<int, double> >’ {aka ‘const double’} discards qualifiers
```

If I change the `camp::tuple` to `std::tuple`, it compiles fine.

Also...in tuple.hpp if I replace the implementation:
```c++
  template <size_t i, typename ... T>
  struct tuple_element<i, camp::tuple<T...>> {
    using type = decltype(camp::get<i>(camp::tuple<T...>{}));
  };
```
with something I took/altered from [cppreference](https://en.cppreference.com/w/cpp/utility/tuple/tuple_element):
```c++
  // recursive case
  template<std::size_t I, class Head, class... Tail>
  struct tuple_element<I, camp::tuple<Head, Tail...>>
      : std::tuple_element<I - 1, camp::tuple<Tail...>>
  { };
 
// base case
  template<class Head, class... Tail>
  struct tuple_element<0, camp::tuple<Head, Tail...>>
  {
      using type = Head;
  };
```
it compiles fine.

@trws @adayton1 Is this an OK change to make? I can submit a PR with the changes and add a test for the const case if so. Also should probably add testing for all the structured binding cases: `const auto`, `const auto &`, `const auto &&`?

**Comment by trws** [comment]
Thanks for finding this @rrsettgast.  I'd be more comfortable with a fix like this, which also seems to work:

```c++
  template <size_t i, typename ... T>
  struct tuple_element<i, camp::tuple<T...>> {
    using type = ::camp::tuple_element_t<i, camp::tuple<T...>>;
  };

  template <size_t i, typename TagList, typename... Elements>
  struct tuple_element<i, camp::tagged_tuple<TagList, Elements...>> {
    using type = ::camp::tuple_element_t<i, camp::tagged_tuple<TagList, Elements...>>;
  };
```

Mainly this is because I'm not sure why `std::tuple_element` seems to be working with a `camp::tuple` there, and I'm not sure it's going to be portable.  It would be great if you'd put together a PR, especially with tests for the other cases.  They should be appropriately covered by the gets, but it absolutely wouldn't hurt to check.

**Comment by rrsettgast** [comment]
@trws I think it works because the specialization of ` tuple_element<i, camp::tuple<T...>>' we are talking about is in the `std` namespace...and not in the `camp` namespace??

```c++
#if defined(__cplusplus) && __cplusplus >= 201703L
namespace std {
  /// This allows structured bindings to be used with camp::tuple
  /// e.g. auto t = make_tuple(1, 2.0);
  ///      auto [a, b] = t;
  template <typename... T>
  struct tuple_size<camp::tuple<T...> > {
    static constexpr size_t value = sizeof...(T);
  };

#if 0
  template <size_t i, typename ... T>
  struct tuple_element<i, camp::tuple<T...>> {
    using type = decltype(camp::get<i>(camp::tuple<T...>{}));
  };
#else  
  // recursive case
  template<std::size_t I, class Head, class... Tail>
  struct tuple_element<I, camp::tuple<Head, Tail...>>
      : std::tuple_element<I - 1, std::tuple<Tail...>>
  { };
 
// base case
  template<class Head, class... Tail>
  struct tuple_element<0, camp::tuple<Head, Tail...>>
  {
      using type = Head;
  };
#endif

...
} // namespace std
```

**Comment by trws** [comment]
Ah, true, it's picking up the same one.  Either way, I prefer avoiding the recursive expansion if possible, if we hit a case where recursive expansion works and the forwarding to `camp::at_v` through `camp::tuple_element_t` does not, I'm fine with it, but generally I try pretty hard to avoid doing recursive walks in the tuple code.  For small ones it doesn't matter a whole lot, but the existing one resolves to the `__type_pack_element` builtin on most compilers, which does help.

**Comment by rrsettgast** [comment]
@trws Sounds good. I'll put that together...but do you understand why the existing implementation was failing? I assume it had to do with the `decltype(camp::get<i>(camp::tuple<T...>{}))` shedding the appropriate `const`ness....but I get really turned around on it. is it:

-  `decltype(camp::get<I>( const camp::tuple<T...>{}))` ,...
- `using type = const decltype(camp::get<i>(camp::tuple<T...>{}))` didn't work when I overloaded...


I assume the structured binding has the compiler creating a temp and that:
```c++
const auto [a,b] = camp::tuple<T...>;
```
is just some type of syntactic sugar for:
```c++
const auto someThingYouNeverSee = camp::tuple<T...>;
const auto a = camp::get<0>(someThingYouNeverSee);
const auto b = camp::get<1>(someThingYouNeverSee);
```
But how is the presence of `const` on the `lhs` dictating the requirement of `const` of the `rhs`? I am so confused 😁 .

**Comment by trws** [comment]
Structured binding is much, much stranger than that, for good or ill.  It's specified such that:

```c++
const auto [a,b] = camp::tuple<T...>;
```
Is roughly equivalent to:
```c++
const auto &&lifetime_extended_rvalue = camp::tuple<T...>;
decltype(auto) a = camp::get<0>(lifetime_extended_rvalue);
decltype(auto) b = camp::get<1>(lifetime_extended_rvalue);
```

I say roughly because you can't write what structured binding does in any other way in C++.  You can take a structured binding of a bitfield:
```c++
    struct BitFields {
        int n : 4, m : 4;
    };
auto [n, m] = BitFields{1, 5};
```

The actual structured binding names are not variables, they are not references, they are aliases that directly correspond to the original storage with the original type, which makes them very, very odd.  Effectively what happens when you put const on the left-hand-side of one of these, is that it applies const to whatever is on the right-hand-side before pulling the field types out.  That's it.  I actually got mixed up looking at the code too because if the right hand side is a tuple full of references, this kind of thing is valid:

```c++
int a1 = 0, b1 =1;
const auto [a, b] = std::tie(a1, b1);
a = 5;
```

If you desugar it all the way out though it starts to make sense, leaving my type annotations in on this one:

```c++
 ┆ int a1 = 0;
 ┆ double b1 =1.1;
 ┆ const auto t = std::tie(a1, b1); : const tuple<int &, double &>
 ┆ const auto [a, b] = t; : int & : double &
 ┆ decltype(auto) a2 = std::get<0>(t); : int &
 ┆ decltype(auto) b2 = std::get<1>(t); : double &
 ┆ auto a3 = std::get<0>(t); : int
 ┆ auto b3 = std::get<1>(t); : double
```
The const on the left makes the *tuple* const, but that doesn't *necessarily* make its contents const.  That's why the get code is so terrifying, it has to retain all reference types and all const qualifications through all of this mess.  When we can ditch C++14, I think about 2/3 of it can just be deleted. 😆

**Comment by rrsettgast** [comment]
@trws I don't have permissions to push a branch...do I need to fork?

**Comment by trws** [comment]
Ah, yes forks are the norm for camp.

**Comment by rrsettgast** [comment]
@trws Thanks for the detailed explanation. I feel less clueless now 😬
